# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - #name: Home
    #url: /
    #weight: 100

  - name: profile
    identifier: profile
    url: profile
    weight: 100
  - name: About me
    parent: profile
    url: about/
    weight: 110
  - name: Interests
    parent: profile
    url: interests/
    weight: 120

  - name: projects
    identifier: projects
    url: project/
    weight: 200

  - name: notice
    identifier: notice
    url: notice/
    weight: 300
  - name: news
    parent: notice
    url: notice/
    weight: 310
  - name: gallery
    parent: notice
    url: gallery
    weight: 320 

  - name: publication
    url: publication/
    weight: 400

  - name: contact
    url: contact/
    weight: 500

  - name: FAQ
    url: faq/
    weight: 600  
    
