# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: profile
    identifier: profiles
    # url: profile/
    weight: 20
  - name: introduction
    parent: profiles
    url: profile/introduction/
    weight: 10
  - name: interests
    parent: profiles
    url: profile/interests/
    weight: 20
  - name: projects
    url: project/
    weight: 30
  - name: contact
    url: contact/
    weight: 40
    
