# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 100

  - name: Experience
    url: experience/
    weight: 200

  - name: Projects
    url: projects/
    weight: 300

  - name: Community
    weight: 400
    identifier: community
  - name: Events
    url: events/
    weight: 410
    parent: community
  - name: Blog
    url: blog/
    weight: 420
    parent: community

  - name: Contact
    url: contact/
    weight: 500

  #- name: Talks
    #url: /#talks
    #weight: 600

  #- name: Courses
    #url: courses/
    #weight: 700
